#!/usr/bin/env python3

# teledown - Script To Download Multiple Telegram Images.

import sys,requests,bs4,re
def downloader(links):
    for i in range(len(links)):
        res = requests.get(links[i])
        try:
            res.raise_for_status()
        except Exception as exc:
            print('Error %s '%(exc))
            continue
        file1 = open(f'output/img{i+1}.jpg','wb')
        for chuck in res.iter_content(1000):
            file1.write(chuck)
        file1.close()
def processor(src):
    url = []
    regex = re.compile(r'https://.*\.jpg')
    for i in src:
        mo = regex.search(i)
        if mo == None:
            continue
        url.append(mo.group())
    return url

def srcimg(listchanl ,num = 0):
    src=[]
    for i in listchanl:
        respObj = requests.get("https://t.me/s/"+i)
        try:
            respObj.raise_for_status()
        except Exception as exc:
            print('Error %s ' %(exc))
            continue
        soupObj = bs4.BeautifulSoup(respObj.text,features='lxml')
        tagObjs = soupObj.select('a[style]')
        if num != 0 and num < len(tagObjs):
            tagObjs = tagObjs[:num]
        for tagObj in tagObjs:
            src.append(tagObj.get('style'))
        return src

helper = open('./config/helper.txt','r').read()

hp = "Try './teledown -h' for more information."

if len(sys.argv) < 2:
    print('teledown: error: no arguments')
    print(hp)
    sys.exit()
elif sys.argv[1] == '-h':
    print(helper)
    sys.exit()
elif sys.argv[1] == '-N':
    if len(sys.argv) > 3 and str(sys.argv[2]).isdecimal():
        print('Please wait')
        listname = sys.argv[3:]
        imageurl = processor(srcimg(listname,int(sys.argv[2])))
        downloader(imageurl)
        sys.exit()
    else:
        print(hp)
        sys.exit()
print('Please wait')
listname = sys.argv[1:]
imageurl = processor(srcimg(listname))
downloader(imageurl)











