#!/usr/bin/env python3

# teledown - Script To Download Multiple Telegram Images.

import sys,requests,bs4,re

def downloader(links):
    count = 0
    for i in range(len(links)):
        try:
            res = requests.get(links[i],timeout=(10))
        except Exception as exc:
            count+=1
            continue
        file1 = open(f'output/img{i+1}.jpg','wb')
        file1.write(res.content)
        file1.close()
    print(f"({count})timeouts")   
def processor(src):
    url = []
    regex = re.compile(r'https://.*\.jpg')
    for i in src:
        mo = regex.search(i)
        if mo == None:
            continue
        url.append(mo.group())
    return url

def srcimg(listchanl ,num = 0):
    src=[]
    for i in listchanl:
        try:
            respObj = requests.get("https://t.me/s/"+i,timeout=(10))
        except:
            print(f"{i} timeout")
            continue
        soupObj = bs4.BeautifulSoup(respObj.text, features="html.parserr")///
        tagObjs = soupObj.select('a[style]')
        if num != 0 and num < len(tagObjs):
            tagObjs = tagObjs[:num]
        print(f"{i}    {len(tagObjs)} found.")    
        for tagObj in tagObjs:
            src.append(tagObj.get('style'))
    return src

helper = open('./config/helper.txt','r').read()

hp = "Try './teledown -h' for more information."

if len(sys.argv) < 2:
    print('teledown: error: no arguments')
    print(hp)
    sys.exit()
elif sys.argv[1] == '-h':
    print(helper)
    sys.exit()
elif sys.argv[1] == '-N':
    if len(sys.argv) > 3 and str(sys.argv[2]).isdecimal():
        print('Please wait'.center(33))
        listname = sys.argv[3:]
        imageurl = processor(srcimg(listname, num = int(sys.argv[2])))
        downloader(imageurl)
        sys.exit()
    else:
        print(hp)
        sys.exit()
print('Please wait'.center(33))
listname = sys.argv[1:]
imageurl = processor(srcimg(listname))
downloader(imageurl)











